# Generated by Django 4.1.3 on 2023-01-27 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('cedula', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('correo', models.CharField(max_length=80)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.tipo_persona')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('estado_curso', models.CharField(max_length=50)),
                ('periodo_lectivo', models.CharField(max_length=50)),
                ('paralelo', models.CharField(max_length=50)),
                ('persona_curso', models.ManyToManyField(to='api.persona')),
            ],
        ),
    ]
